version: "3"
services:
  # Instances: 0: "10.10.25.49",  1: "10.10.18.147", 2: "10.10.31.171"
  # ["10.10.25.49",  "10.10.18.147", "10.10.31.171"]
  # consul-0: Bootstrap consul server
  consul-bootstrap:
    container_name: consul.server.bootstrap
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -advertise 10.10.25.49 -disable-host-node-id true -config-dir /consul/config
    image: consul:latest
    volumes:
      - ./consul.server/config-bootstrap:/consul/config
      - /ebs/docker_volumes/consul_data_0:/consul/data
    ports:
      - "9300:9300"
      - "9301:9301"
      - "9302:9302"
      - "9500:9500"
      - "9600:9600/udp"

  consul-0:
    container_name: consul.server.0
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -advertise 10.10.25.49 -disable-host-node-id true -config-dir /consul/config
    image: consul:latest
    volumes:
      - ./consul.server/config-0:/consul/config
      - /ebs/docker_volumes/consul_data_0:/consul/data
    ports:
      - "9300:9300"
      - "9301:9301"
      - "9302:9302"
      - "9500:9500"
      - "9600:9600/udp"

  vault-0:
    container_name: vault.server.0
    image: vault:latest
    ports:
      - "9200:8200"
    volumes:
      - /ebs/docker_volumes/vault.server/config:/mnt/vault/config
      - /ebs/docker_volumes/vault.server/data:/mnt/vault/data
      - /ebs/docker_volumes/vault.server/logs:/mnt/vault/logs
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_LOCAL_CONFIG={"backend":{"consul":{"address":"${LOCAL_IP}:9500","advertise_addr":"http://${LOCAL_IP}", "path":"vault/"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}}}
    command: server

  bash_test:
    container_name: bash.test
    build: ./bash_test
    environment:
      - CONSUL_HTTP_ADDR=${LOCAL_IP}:9500
      - VAULT_ADDR=http://${LOCAL_IP}:9200
    volumes:
      - /ebs/docker_volumes/bash.test/data:/mnt/data
    command: tail -f /dev/null
    tty: true
    stdin_open: true